services:
    contao_company.listener.insert_tags:
        class: Oveleon\ContaoCompanyBundle\EventListener\InsertTagsListener
        arguments:
            - '@router.default'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }
        public: true
